version: '3'
services:
  web:
    restart: unless-stopped
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./client/.
    ports:
      - '3000:3000'
    volumes:
      - /app/client/node_modules
      - ./client/.:/app/client
  node:
    restart: always
    build: ./server/.
    ports:
        - "8080:8080"
    environment:
      - MONGO_USERNAME=user
      - MONGO_PASSWORD=pass
      # - MONGO_HOSTNAME=127.0.0.1
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - MONGO_DB=newdb
    volumes:
        - /app/server/node_modules
        - ./server/.:/app/server
  mongo:
    restart: unless-stopped
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongodb:/data/db
